[deps.prelude]
git = "https://github.com/StratifyLabs/buck2-prelude"
branch = "main"
rev = "0f14d88c8e36ef018c2d2c17e46cab250cd7c1ba"

[archives.stratifyos_arm_none_eabi]
url = "https://github.com/StratifyLabs/SDK/releases/download/v11.3.1/stratifyos-arm-none-eabi-11.3.1.zip"
sha256 = "a8a3d4da94e030730aaa34cb4983fbe13724d818fbc11006fcace6233b167c14"
link = "Hard"