[vscode.extensions]
recommendations = ["llvm-vs-code-extensions.vscode-clangd"]

[assets.'spaces_assets/profile.sh']
path = "sdk_profile.sh"
type = "HardLink"

[assets.'spaces_assets/clang-format']
path = ".clang-format"
type = "HardLink"

[assets.'spaces_assets/clangd.json']
path = ".clangd"
type = "HardLink"

[deps.prelude]
git = "https://github.com/StratifyLabs/buck2-prelude"
branch = "main"
rev = "0f14d88c8e36ef018c2d2c17e46cab250cd7c1ba"

[archives.stratifyos_arm_none_eabi]
url = "https://github.com/StratifyLabs/SDK/releases/download/v11.3.1/stratifyos-arm-none-eabi-11.3.1.zip"
sha256 = "d32b82768b4d6c1f106a32182b386164fccd72863c7d558b3fef129281780ac4"
link = "Hard"
add_prefix = "{SPACES_SYSROOT}"


[platform_archives.sl.macos_x86_64]
url = "https://github.com/StratifyLabs/sl2/releases/download/v2.0/sl-macos-x86_64.zip"
sha256 = "5c8f84c23655b6de4222bd4df72a399f3a53efc367bed5ed0db9e9320014ee92"
add_prefix = "{SPACES_SYSROOT}/bin"
link = "Hard"

[platform_archives.sl.windows_x86_64]
url = "https://github.com/StratifyLabs/sl2/releases/download/v2.0/sl-windows-x86_64.zip"
sha256 = "5787d28ee13013cbf5d848b8cd3c115087735781375934e848fa917436031f2a"
add_prefix = "{SPACES_SYSROOT}/bin"
link = "Hard"



